# Site settings
title: Julien Giffard
email: julien.giffard@gmail.com
domain: juliengiffard.com
url: https://juliengiffard.com
description: "Développeur Javascript Fullstack"
author: "Julien Giffard"
headTitle: "Julien Giffard : Développeur Fullstack sur Toulouse"
metaDescription: "Découvrez mon CV de développeur Javascript full-stack sur Toulouse, Haute-Garonne (31)."
baseurl: ""
# Build settings
markdown: kramdown
permalink: pretty
compress_html:
  clippings: []
  comments: ["<!-- ", " -->"]
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
exclude:
- package.json
- README.md
- .idea/
